# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\o_0\Documents\IIPCVDL\Hw1_5\interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWidget(object):
    def setupUi(self, MainWidget):
        MainWidget.setObjectName("MainWidget")
        MainWidget.resize(300, 400)
        self.groupBox = QtWidgets.QGroupBox(MainWidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 281, 381))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.btn1 = QtWidgets.QPushButton(self.groupBox)
        self.btn1.setGeometry(QtCore.QRect(40, 30, 200, 30))
        self.btn1.setObjectName("btn1")
        self.btn2 = QtWidgets.QPushButton(self.groupBox)
        self.btn2.setGeometry(QtCore.QRect(40, 90, 200, 30))
        self.btn2.setObjectName("btn2")
        self.btn3 = QtWidgets.QPushButton(self.groupBox)
        self.btn3.setGeometry(QtCore.QRect(40, 150, 200, 30))
        self.btn3.setObjectName("btn3")
        self.btn4 = QtWidgets.QPushButton(self.groupBox)
        self.btn4.setGeometry(QtCore.QRect(40, 210, 200, 30))
        self.btn4.setObjectName("btn4")
        self.btn5 = QtWidgets.QPushButton(self.groupBox)
        self.btn5.setGeometry(QtCore.QRect(40, 320, 200, 30))
        self.btn5.setObjectName("btn5")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox.setGeometry(QtCore.QRect(40, 270, 200, 30))
        self.spinBox.setMaximum(9999)
        self.spinBox.setObjectName("spinBox")

        self.retranslateUi(MainWidget)
        QtCore.QMetaObject.connectSlotsByName(MainWidget)

    def retranslateUi(self, MainWidget):
        _translate = QtCore.QCoreApplication.translate
        MainWidget.setWindowTitle(_translate("MainWidget", "Hw1_5"))
        self.btn1.setText(_translate("MainWidget", "1.Show Train Images"))
        self.btn2.setText(_translate("MainWidget", "2.Show Hyperparameters"))
        self.btn3.setText(_translate("MainWidget", "3.Show Model Structure"))
        self.btn4.setText(_translate("MainWidget", "4.Show Accuracy"))
        self.btn5.setText(_translate("MainWidget", "5.Test"))
